# Generated by Django 4.1.5 on 2023-02-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
    ]
