# Generated by Django 4.1.5 on 2023-03-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0005_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="average_rating",
            field=models.FloatField(default=0, verbose_name="Average Rating"),
        ),
        migrations.AddField(
            model_name="movie",
            name="num_rating",
            field=models.IntegerField(default=0, verbose_name="Number of Rating"),
        ),
    ]
