# Generated by Django 4.1.5 on 2023-01-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="votes",
        ),
        migrations.AddField(
            model_name="choice",
            name="votes",
            field=models.IntegerField(default=0, verbose_name="Votes"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to="polls.poll",
                verbose_name="Poll",
            ),
        ),
    ]
