# Generated by Django 4.1.5 on 2023-01-16 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_remove_choice_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="polls.poll",
                verbose_name="Poll",
            ),
        ),
    ]
